[versions]
kotlin-build = "1.9.0"
#noinspection UnusedVersionCatalogEntry
kotlin-latest = "2.4.20-RC2"
#noinspection AndroidGradlePluginVersion
agp-build = "8.12.0"
#noinspection UnusedVersionCatalogEntry
agp-latest = "9.4.0-rc01"
#noinspection NewerVersionAvailable
coroutines-build = "1.8.1"
coroutines-latest = "1.11.0"
#noinspection NewerVersionAvailable
jackson = "2.19.2"
plugin-shadow = "9.2.2"
plugin-dokka = "1.9.20"
plugin-gradle-publish = "2.0.0"
android-compile-sdk = "36"
#noinspection NewerVersionAvailable
jupiter = "5.10.5"

[libraries]
asm-utils = { group = "org.ow2.asm", name = "asm-util", version = "9.10.1" }
dalvik-dx = { group = "com.jakewharton.android.repackaged", name = "dalvik-dx", version = "16.0.1" }
#noinspection GradleDependency
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.5.2" }
#noinspection GradleDependency
androidx-test-monitor = { group = "androidx.test", name = "monitor", version = "1.6.0" }
#noinspection NewerVersionAvailable
kotlin-logging-jvm = { group = "io.github.oshai", name = "kotlin-logging-jvm", version = "7.0.0" }
#noinspection GradleDependency
kotlin-gradle-plugin-api = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api", version = "1.7.0" }
byte-buddy-agent = { group = "net.bytebuddy", name = "byte-buddy-agent", version = "1.18.12" }
#noinspection NewerVersionAvailable
ktor-io-jvm = { group = "io.ktor", name = "ktor-io-jvm", version = "2.0.1" }
jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiter" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiter" }
junit4 = { group = "junit", name = "junit", version = "4.13.2" }
#noinspection SimilarGradleDependency
coroutines-core-build = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines-build" }
#noinspection SimilarGradleDependency
coroutines-core-latest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines-latest" }
#noinspection SimilarGradleDependency
coroutines-debug-build = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version.ref = "coroutines-build" }
#noinspection SimilarGradleDependency,UnusedVersionCatalogEntry
coroutines-debug-latest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-debug", version.ref = "coroutines-latest" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
kotlin-metadata-jvm = { group = "dev.reformator.kotlin-metadata-jvm-repack", name = "kotlin-metadata-jvm-repack", version = "0.9.0-3" }
#noinspection NewerVersionAvailable
ant = { group = "org.apache.ant", name = "ant", version = "1.10.15" }
android-gradle-plugin-build = { group = "com.android.tools.build", name = "gradle", version.ref = "agp-build" }
#noinspection NewerVersionAvailable
junit5-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.14.3" }
bytecode-processor-intrinsics = { group = "dev.reformator.bytecodeprocessor", name = "bytecode-processor-intrinsics" }
bytecode-processor-api = { group = "dev.reformator.bytecodeprocessor", name = "bytecode-processor-api" }
decoroutinator-clazz-transformer = { group = "dev.reformator.stacktracedecoroutinator", name = "stacktrace-decoroutinator-class-transformer"}
decoroutinator-intrinsics = { group = "dev.reformator.stacktracedecoroutinator", name = "intrinsics" }
decoroutinator-tests = { group = "dev.reformator.stacktracedecoroutinator", name = "tests" }
decoroutinator-generator-jvm = { group = "dev.reformator.stacktracedecoroutinator", name = "stacktrace-decoroutinator-generator-jvm" }
decoroutinator-generator-android = { group = "dev.reformator.stacktracedecoroutinator", name = "stacktrace-decoroutinator-generator-android" }
decoroutinator-mh-invoker = { group = "dev.reformator.stacktracedecoroutinator", name = "stacktrace-decoroutinator-mh-invoker"}
decoroutinator-naive-base-continuation-accessor = { group = "dev.reformator.stacktracedecoroutinator", name = "naive-base-continuation-accessor" }
decoroutinator-methods-with-spaces-tests = { group = "dev.reformator.stacktracedecoroutinator", name = "methods-with-spaces-tests" }
decoroutinator-aar = { group = "dev.reformator.stacktracedecoroutinator", name = "aar" }
decoroutinator-mh-invoker-jvm = { group = "dev.reformator.stacktracedecoroutinator", name = "stacktrace-decoroutinator-mh-invoker-jvm" }
decoroutinator-common = { group = "dev.reformator.stacktracedecoroutinator", name = "stacktrace-decoroutinator-common" }
decoroutinator-provider = { group = "dev.reformator.stacktracedecoroutinator", name = "stacktrace-decoroutinator-provider" }

[plugins]
shadow = { id = "com.gradleup.shadow" }
dokka = { id = "org.jetbrains.dokka" }
gradle-publish = { id = "com.gradle.plugin-publish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
kotlin-android = { id = "org.jetbrains.kotlin.android" }
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
bytecode-processor = { id = "dev.reformator.bytecode-processor" }
force-variant-java-version = { id = "dev.reformator.force-variant-java-version" }
delete-signature-checksums = { id = "dev.reformator.delete-signature-checksums" }
decoroutinator-transform-base-continuation = { id = "dev.reformator.decoroutinator-transform-base-continuation" }
decoroutinator = { id = "dev.reformator.stacktracedecoroutinator" }
root-dependencies-loader = { id = "dev.reformator.root-dependencies-loader" }
