@file:Suppress("PackageDirectoryMismatch")
@file:JvmName("DecoroutinatorProviderApiKt")

package dev.reformator.stacktracedecoroutinator.provider

import dev.reformator.bytecodeprocessor.intrinsics.GetOwnerClass
import dev.reformator.bytecodeprocessor.intrinsics.MethodNameConstant
import dev.reformator.bytecodeprocessor.intrinsics.fail
import dev.reformator.stacktracedecoroutinator.provider.internal.AndroidLegacyKeep
import dev.reformator.stacktracedecoroutinator.provider.internal.BaseContinuationAccessor
import dev.reformator.stacktracedecoroutinator.provider.internal.doVerifySharedSpec
import dev.reformator.stacktracedecoroutinator.provider.internal.intIdentity
import dev.reformator.stacktracedecoroutinator.provider.internal.minusKey
import dev.reformator.stacktracedecoroutinator.provider.internal.enabled
import dev.reformator.stacktracedecoroutinator.provider.internal.fillUnknownElementsWithClassName as cachedFillUnknownElementsWithClassName
import dev.reformator.stacktracedecoroutinator.provider.internal.isUsingElementCacheForManualContinuationGetElementMethodEnabled as cachedIsUsingElementCacheForManualContinuationGetElementMethodEnabled
import dev.reformator.stacktracedecoroutinator.provider.internal.isUsingElementCacheForLazilyCachedContinuationGetElementMethodEnabled as cachedIsUsingElementCacheForLazilyCachedContinuationGetElementMethodEnabled
import dev.reformator.stacktracedecoroutinator.provider.internal.isUsingElementFactoryForBaseContinuationEnabled as cachedIsUsingElementFactoryForBaseContinuationEnabled
import dev.reformator.stacktracedecoroutinator.provider.internal.nullElementSpecCache as cachedNullElementSpecCache
import dev.reformator.stacktracedecoroutinator.provider.internal.provider
import dev.reformator.stacktracedecoroutinator.provider.internal.randomInt
import dev.reformator.stacktracedecoroutinator.provider.internal.resume
import dev.reformator.stacktracedecoroutinator.provider.internal.tailCallDeoptimize as cachedTailCallDeoptimize
import dev.reformator.stacktracedecoroutinator.provider.internal.transformedClassesRegistry
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

@Suppress("unused", "FunctionName", "PropertyName")
@AndroidLegacyKeep
interface DecoroutinatorSpec {
    val `$decoroutinator$resumeCookie`: Any?

    val `$decoroutinator$checksumFailedMarker`: ChecksumFailedMarker
        get() = ChecksumFailedMarker

    fun `$decoroutinator$getResumeChecksum`(resumeChecksum: Int, resumeCookie: Any?): Int

    val `$decoroutinator$lineNumber`: Int

    val `$decoroutinator$nextSpecHandle`: MethodHandle?

    val `$decoroutinator$nextSpec`: DecoroutinatorSpec?

    fun `$decoroutinator$resume`(result: Any?, resumeChecksum: Int, depthChecksum: Int, resumeCookie: Any?): Any?
}

// Depth-check bail-out (see common/awakener.kt's per-dispatch decrement) needs its sentinel's TYPE to be
// public, since it's exposed as $decoroutinator$checksumFailedMarker's return type on the public
// DecoroutinatorSpec interface - Kotlin won't let a public member expose an internal type. The
// Any?.isChecksumFailedMarker Boolean extension used to test a value against this marker stays internal
// in utils-provider.kt (used only by plain compiled Kotlin code - resume() there and awakener.kt's
// top-level retry check - never by generated bytecode, which instead fetches this marker via
// $decoroutinator$checksumFailedMarker and compares by reference directly); only the marker object
// itself needs to live here, publicly.
object ChecksumFailedMarker

@Suppress("PrivatePropertyName", "FunctionName")
open class SharedSpec: DecoroutinatorSpec {
    @Transient private var `$decoroutinator$accessor`: BaseContinuationAccessor? = null
    @Transient private var `_$decoroutinator$lineNumber`: Int = 0
    @Transient private var `_$decoroutinator$nextSpec`: DecoroutinatorSpec? = null
    @Transient private var `_$decoroutinator$nextSpecHandle`: MethodHandle? = null
    @Transient private var `$decoroutinator$nextContinuation`: Any? = null

    @Suppress("unused")
    fun `$decoroutinator$init`(
        accessor: BaseContinuationAccessor,
        lineNumber: Int,
        nextSpec: DecoroutinatorSpec?,
        nextSpecHandle: MethodHandle?,
        nextContinuation: Any?
    ) {
        `$decoroutinator$accessor` = accessor
        `_$decoroutinator$lineNumber` = lineNumber
        `_$decoroutinator$nextSpec` = nextSpec
        `_$decoroutinator$nextSpecHandle` = nextSpecHandle
        `$decoroutinator$nextContinuation` = nextContinuation
    }

    override val `$decoroutinator$resumeCookie`: Any?
        get() = `$decoroutinator$nextContinuation`

    override fun `$decoroutinator$getResumeChecksum`(resumeChecksum: Int, resumeCookie: Any?): Int =
        if (doVerifySharedSpec && resumeCookie != null) {
            resumeChecksum minusKey resumeCookie.intIdentity
        } else {
            resumeChecksum
        }

    override val `$decoroutinator$lineNumber`: Int
        get() = `_$decoroutinator$lineNumber`

    override val `$decoroutinator$nextSpecHandle`: MethodHandle?
        get() = `_$decoroutinator$nextSpecHandle`

    override val `$decoroutinator$nextSpec`: DecoroutinatorSpec?
        get() = `_$decoroutinator$nextSpec`

    override fun `$decoroutinator$resume`(
        result: Any?,
        resumeChecksum: Int,
        depthChecksum: Int,
        resumeCookie: Any?
    ): Any? =
        resume(result, resumeChecksum, resumeCookie) { baseContinuation, resultCopy ->
            provider.callInvokeSuspendIfResultIsNotCoroutineSuspended(
                baseContinuation = baseContinuation,
                accessor = `$decoroutinator$accessor`!!,
                result = resultCopy
            )
        }
}

@Suppress("PropertyName")
interface HasIntIdentity {
    @Suppress("unused")
    val `$decoroutinator$intIdentity`: Int
}

open class SharedSpecWithIntIdentity: SharedSpec(), HasIntIdentity {
    override val `$decoroutinator$intIdentity` = if (doVerifySharedSpec) randomInt() else 0
}

@Suppress("unused")
@Target(AnnotationTarget.CLASS, AnnotationTarget.FILE)
@Retention
annotation class DecoroutinatorTransformed(
    @Suppress("unused")
    @get:MethodNameConstant("decoroutinatorTransformedFileNamePresentMethodName")
    @get:JvmName("fnp")
    val fileNamePresent: Boolean = true,

    @get:MethodNameConstant("decoroutinatorTransformedFileNameMethodName")
    @get:JvmName("fn")
    val fileName: String = "",

    @get:MethodNameConstant("decoroutinatorTransformedClassNameMethodName")
    @get:JvmName("cn")
    val className: String = "",

    @get:MethodNameConstant("decoroutinatorTransformedModeMethodName")
    @get:JvmName("m")
    val mode: Mode = Mode.FULL
) {
    enum class Mode {
        FULL, SKIP_SPEC_METHODS, PRESERVE_CLASS_LAYOUT
    }
}

@Suppress("unused")
@Target(AnnotationTarget.FUNCTION)
@Retention
annotation class DecoroutinatorSpecMethod(
    @get:MethodNameConstant("decoroutinatorSpecMethodMethodNameMethodName")
    @get:JvmName("mn")
    val methodName: String,

    @get:MethodNameConstant("decoroutinatorSpecMethodLineNumbersMethodName")
    @get:JvmName("ln")
    val lineNumbers: IntArray
)

interface ContinuationCached {
    @Suppress("unused", "PropertyName")
    val `$decoroutinator$cache`: SpecCache?
}

interface BaseContinuationExtractor: ContinuationCached {
    @Suppress("PropertyName")
    @get:MethodNameConstant("baseContinuationExtractorGetLabelMethodName")
    val `$decoroutinator$label`: Int

    @Suppress("PropertyName")
    @get:MethodNameConstant("baseContinuationExtractorGetCachesMethodName")
    val `$decoroutinator$caches`: Array<SpecCache>

    override val `$decoroutinator$cache`: SpecCache
        get() = `$decoroutinator$caches`[`$decoroutinator$label` and Int.MAX_VALUE]
}

interface ManualContinuation: ContinuationCached {
    @Suppress("PropertyName")
    @get:MethodNameConstant("manualContinuationGetCacheFieldMethodName")
    val `$decoroutinator$cacheField`: SpecCache

    @Suppress("PropertyName")
    @get:MethodNameConstant("manualContinuationGetClassMethodName")
    val `$decoroutinator$class`: Class<*>

    @get:MethodNameConstant("manualContinuationGetCacheMethodName")
    override val `$decoroutinator$cache`: SpecCache?
        get() = when {
            !cachedFillUnknownElementsWithClassName -> cachedNullElementSpecCache
            javaClass !== `$decoroutinator$class` -> null
            else -> `$decoroutinator$cacheField`
        }
}

interface LazilyCachedContinuation: ContinuationCached {
    @Suppress("PropertyName")
    @get:MethodNameConstant("lazilyCachedContinuationGetCacheFieldMethodName")
    @set:MethodNameConstant("lazilyCachedContinuationSetCacheFieldMethodName")
    var `$decoroutinator$cacheField`: SpecCache?

    override val `$decoroutinator$cache`: SpecCache
        get() {
            val cacheField = `$decoroutinator$cacheField`
            return if (cacheField == null) {
                val element = provider.getCoroutineStackFrameStackTraceElement(this)
                val result = if (element == null) {
                    if (cachedFillUnknownElementsWithClassName) {
                        SpecCache(javaClass.name, "resumeWith", null, -1)
                    } else cachedNullElementSpecCache
                } else SpecCache(element)
                `$decoroutinator$cacheField` = result
                result
            } else cacheField
        }
}

@Suppress("unused")
class SpecCache(
    @get:MethodNameConstant("specCacheGetElementMethodName")
    val element: StackTraceElement?
) {
    var specMethod: MethodHandle? = null

    constructor(
        className: String,
        methodName: String,
        fileName: String?,
        lineNumber: Int
    ): this(StackTraceElement(
        className,
        methodName,
        fileName,
        lineNumber
    ))
}

@Suppress("unused")
val isDecoroutinatorEnabled: Boolean
    @MethodNameConstant("isDecoroutinatorEnabledMethodName") get() = enabled

@Suppress("unused")
@MethodNameConstant("registerTransformedClassMethodName")
fun registerTransformedClass(lookup: MethodHandles.Lookup) {
    transformedClassesRegistry.registerTransformedClass(lookup)
}

@Suppress("unused")
val isTailCallDeoptimizationEnabled: Boolean
    @MethodNameConstant("isTailCallDeoptimizationEnabledMethodName")
    get() = cachedTailCallDeoptimize

@Suppress("unused")
@MethodNameConstant("tailCallDeoptimizeMethodName")
fun tailCallDeoptimize(completion: Any, cache: SpecCache?): Any =
    provider.tailCallDeoptimize(completion, cache)

@Suppress("unused")
val isUsingElementFactoryForBaseContinuationEnabled: Boolean
    @MethodNameConstant("isUsingElementFactoryForBaseContinuationEnabledMethodName")
    get() = cachedIsUsingElementFactoryForBaseContinuationEnabled

@Suppress("unused")
val fillUnknownElementsWithClassName: Boolean
    @MethodNameConstant("fillUnknownElementsWithClassNameMethodName")
    get() = cachedFillUnknownElementsWithClassName

@Suppress("unused")
val isUsingElementCacheForManualContinuationGetElementMethodEnabled: Boolean
    @MethodNameConstant("isUsingElementCacheForManualContinuationGetElementMethodEnabledMethodName")
    get() = cachedIsUsingElementCacheForManualContinuationGetElementMethodEnabled

@Suppress("unused")
val isUsingElementCacheForLazilyCachedContinuationGetElementMethodEnabled: Boolean
    @MethodNameConstant("isUsingElementCacheForLazilyCachedContinuationGetElementMethodEnabledMethodName")
    get() = cachedIsUsingElementCacheForLazilyCachedContinuationGetElementMethodEnabled

val providerApiClass: Class<*>
    @GetOwnerClass get() { fail() }
