name: Run Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Configure Gradle memory
        run: mkdir -p ~/.gradle && echo "org.gradle.jvmargs=-Xmx2g" >> ~/.gradle/gradle.properties

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Initialize test build
        run: ./gradlew initTestsBuild && echo "sdk.dir=$ANDROID_SDK_ROOT" > _tests/local.properties

      - name: Run root build's tests
        run: ./gradlew test

      - name: Run test build's tests
        working-directory: _tests
        run: ../gradlew test

      - name: Build test build's android-gradle-plugin-tests APKs
        working-directory: _tests
        run: ../gradlew :android:gradle-plugin-tests:assembleDebug :android:gradle-plugin-tests:assembleDebugAndroidTest

      - name: Run test build's android-gradle-plugin-tests on API 26
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --results-bucket=decoroutinator-tests-results \
            --app _tests/android/gradle-plugin-tests/build/outputs/apk/debug/gradle-plugin-tests-debug.apk \
            --test _tests/android/gradle-plugin-tests/build/outputs/apk/androidTest/debug/gradle-plugin-tests-debug-androidTest.apk \
            --device model=Pixel2.arm,version=26,locale=en \
            --no-record-video \
            --timeout 1m

      - name: Run test build's android-gradle-plugin-tests on API 36
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --results-bucket=decoroutinator-tests-results \
            --app _tests/android/gradle-plugin-tests/build/outputs/apk/debug/gradle-plugin-tests-debug.apk \
            --test _tests/android/gradle-plugin-tests/build/outputs/apk/androidTest/debug/gradle-plugin-tests-debug-androidTest.apk \
            --device model=tokay,version=36,locale=en \
            --no-record-video \
            --timeout 1m

      - name: Build test build's android-wrong-generator-tests APKs
        working-directory: _tests
        run: ../gradlew :android:wrong-generator-tests:assembleDebug :android:wrong-generator-tests:assembleDebugAndroidTest

      - name: Run test build's android-wrong-generator-tests on API 26
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --results-bucket=decoroutinator-tests-results \
            --app _tests/android/wrong-generator-tests/build/outputs/apk/debug/wrong-generator-tests-debug.apk \
            --test _tests/android/wrong-generator-tests/build/outputs/apk/androidTest/debug/wrong-generator-tests-debug-androidTest.apk \
            --device model=Pixel2.arm,version=26,locale=en \
            --no-record-video \
            --timeout 1m

      - name: Build test build's android-legacy-gradle-plugin-tests APKs
        working-directory: _tests
        run: ../gradlew :android-legacy:gradle-plugin-tests:assembleDebug :android-legacy:gradle-plugin-tests:assembleDebugAndroidTest

      - name: Run test build's android-legacy-gradle-plugin-tests on API 26
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --results-bucket=decoroutinator-tests-results \
            --app _tests/android-legacy/gradle-plugin-tests/build/outputs/apk/debug/gradle-plugin-tests-debug.apk \
            --test _tests/android-legacy/gradle-plugin-tests/build/outputs/apk/androidTest/debug/gradle-plugin-tests-debug-androidTest.apk \
            --device model=Pixel2.arm,version=26,locale=en \
            --no-record-video \
            --timeout 1m

      - name: Run test build's android-legacy-gradle-plugin-tests on API 23
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --results-bucket=decoroutinator-tests-results \
            --app _tests/android-legacy/gradle-plugin-tests/build/outputs/apk/debug/gradle-plugin-tests-debug.apk \
            --test _tests/android-legacy/gradle-plugin-tests/build/outputs/apk/androidTest/debug/gradle-plugin-tests-debug-androidTest.apk \
            --device model=1610,version=23,locale=en \
            --no-record-video \
            --timeout 1m
